#!/usr/bin/env bash

{
    SELFILE="${NNN_SEL:-$HOME/.config/nnn/.selection}"
    if [ -f "$SELFILE" ] && [ -s "$SELFILE" ]; then
        # Pipe the null-separated paths directly
        cat "$SELFILE" | tr '\n' '\0' |
            xargs -0 -I{} realpath "{}" |
            sed 's|^|file://|' |
            xclip -i -selection clipboard -t text/uri-list
        echo "" >"$SELFILE" # Clear selection after use
    else
        # Handle single file case by piping it directly as well
        printf "%s\0" "$PWD/$nnn" |
            xargs -0 -I{} realpath "{}" |
            sed 's|^|file://|' |
            xclip -i -selection clipboard -t text/uri-list
    fi
} >/dev/null 2>&1 &

